# Solution of Exercise 2: numpy

In [2]:
import numpy as np

## Problem 1: 

Compute
$$
   \left[ \begin{array}{ccc}
   3 &  2 & 1 \\
   6 & -3 & 0 \\
   1 &  2 & 9 \\
   \end{array} \right]
   \left[ \begin{array}{ccc}
   -4 & 1 \\
    7 & 3 \\
    2 & 5 \\
   \end{array} \right]
$$
using **matrix** objects

In [3]:
############
# solution
############

A = np.matrix([[3,2,1],[6,-3,0],[1,2,9]])
B = np.matrix([[-4,1],[7,3],[2,5]])
C = A*B

print(C)

[[  4  14]
 [-45  -3]
 [ 28  52]]


Compute
$$
   \left[ \begin{array}{ccc}
   3 &  2 & 1 \\
   6 & -3 & 0 \\
   1 &  2 & 9 \\
   \end{array} \right]
   \left[ \begin{array}{ccc}
   -4 & 1 \\
    7 & 3 \\
    2 & 5 \\
   \end{array} \right]
$$
using **array** objects

In [4]:
D = np.array(A)
E = np.array(B)
F = D@B

print(F)

[[  4  14]
 [-45  -3]
 [ 28  52]]


In [6]:
D*D

array([[ 9,  4,  1],
       [36,  9,  0],
       [ 1,  4, 81]])

In [7]:
D@D

array([[22,  2, 12],
       [ 0, 21,  6],
       [24, 14, 82]])

In [8]:
D

array([[ 3,  2,  1],
       [ 6, -3,  0],
       [ 1,  2,  9]])

In [14]:
D[1,:]

array([ 6, -3,  0])

In [15]:
D[:,0]

array([3, 6, 1])

## Problem 2: 

Numpy provides random number generators for different distributions.
You can find simple examples at [https://numpy.org/doc/stable/reference/random/index.html](https://numpy.org/doc/stable/reference/random/index.html)

1. Write a function that outputs a list of 250 numbers in a normal distribution with (approximately) mean of 2.5 and standard deviation of 0.75. (check [https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html#numpy.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html#numpy.random.normal))
2. Write a loop that uses this function to create 10 instances of such lists. Compute the actual mean and standard deviation and print them.
3. Verify that the answers are indeed random by running your code multiple times.

In [18]:
############
# solution
############

def getList():
    return np.random.normal(2.5, 0.75, 250)
    
for i in range(10):
    data = getList()
    print("avg={:16.8f}, std={:16.8f}".format(np.mean(data), np.std(data)))

avg=      2.48316127, std=      0.75396133
avg=      2.46886291, std=      0.70240595
avg=      2.55646328, std=      0.75839206
avg=      2.54295133, std=      0.76662737
avg=      2.49784438, std=      0.74159536
avg=      2.55916261, std=      0.71578500
avg=      2.40999285, std=      0.74476524
avg=      2.39792024, std=      0.72966319
avg=      2.57386681, std=      0.74606481
avg=      2.53764234, std=      0.70501758


## Problem 3: 

1. Compute and print the eigenvalues, $\lambda_i$, and eigenvectors, ${\bf n}_i$, of
$$
   {\bf A} =
   \left[ \begin{array}{ccccc}
   3 & 2 & 1 & 0 & 0 \\
   2 & 3 & 2 & 1 & 0 \\
   1 & 2 & 3 & 2 & 1 \\
   0 & 1 & 2 & 3 & 2 \\
   0 & 0 & 1 & 2 & 3 
   \end{array} \right]
$$
2. Show that
$$
   {\rm det}({\bf A}) = \prod_{i=1}^5 \lambda_i
$$
3. Verify the following relation
$$
   {\bf A} = \sum_{i=1}^{5} \lambda_i\,{\bf n}_i\otimes{\bf n}_i
$$

In [24]:
############
# solution
############

# 1.
A = np.array([
    [3,2,1,0,0],
    [2,3,2,1,0],
    [1,2,3,2,1],
    [0,1,2,3,2],
    [0,0,1,2,3]
])

(lam,v) = np.linalg.eig(A)

for i in range(5):
    lami = lam[i]
    ni = v[:,i]
    print("lambda={:f} with n={}".format(lami,ni))

# 2.
d = 1
for x in lam:
    d *= x

print(np.linalg.det(A), d)

diff = np.linalg.det(A) - d
reldiff = diff / d
    
if ( np.abs(reldiff) < 1.e-12 ):
    print("it's the same")
else:
    print(f"it's NOT the same: diff = {diff}  rel diff = {reldiff}")

# 3.
B = np.zeros((5,5))
for i in range(5):
    ni = v[:,i]
    B += lam[i] * np.outer(ni,ni)
    
print(np.linalg.norm(A),np.linalg.norm(B),np.linalg.norm(A-B))

lambda=7.654273 with n=[0.3287337  0.48567647 0.55866362 0.48567647 0.3287337 ]
lambda=4.561553 with n=[ 5.57345410e-01  4.35162146e-01 -4.95995854e-16 -4.35162146e-01
 -5.57345410e-01]
lambda=1.747703 with n=[ 0.61754841 -0.17829779 -0.41675859 -0.17829779  0.61754841]
lambda=0.438447 with n=[ 4.35162146e-01 -5.57345410e-01 -3.76589109e-15  5.57345410e-01
 -4.35162146e-01]
lambda=0.598024 with n=[ 0.10280135 -0.48200442  0.71708245 -0.48200442  0.10280135]
15.999999999999991 16.000000000000036
it's the same
9.1104335791443 9.110433579144308 1.6597609081494157e-14


In [30]:
if ( np.abs( 0.1 + 0.2 - 0.3 ) < 1.e-12 ):
    print("YES!")
else:
    print("what is going on here?")

YES!


In [28]:
0.1 + 0.2 - 0.3

5.551115123125783e-17